#!/bin/bash

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
src=$1
# dst=~/Temp/Photos
dst=~/Pictures/Photos
jpg_dir="$3"
raw_type="$2"
raws=`find $src -type f -iname "*.$raw_type"`
raws_cnt=$(echo "$raws" | grep -v ^$ | wc -l)
jpgs=`find $src -type f -iname "*.JPG"`
jpgs_cnt=$(echo "$jpgs" | grep -v ^$ | wc -l)
before_cnt=`find $dst -type f -iregex ".*/01-.*/[^.].*" | wc -l`
img_cnt=$(echo -e "${raws}\n${jpgs}" | grep -v ^$ | sed -e 's;.*/;;' | cut -d. -f1 | sort -u | wc -l)

echo "$img_cnt images ($raws_cnt ${raw_type}s, $jpgs_cnt JPGs)"

copyFiles() {
for file in $1
do
    path="$dst/$(exiftool -d '%Y/%m-%d' -s -s -s -DateTimeOriginal $file)/01-$2"
    if [ ! -e "$path/${file##/*/}" ]
    then
        echo $file
        mkdir -p $path
        cp -n $file $path
    fi
done
}

copyFiles "$raws" "$raw_type"
copyFiles "$jpgs" "$jpg_dir"

echo "$img_cnt images ($raws_cnt ${raw_type}s, $jpgs_cnt JPGs)"

after_cnt=`find $dst -type f -iregex ".*/01-.*/[^.].*" | wc -l`
cp_cnt=$((after_cnt - before_cnt ))
if [ $cp_cnt -eq $((raws_cnt + jpgs_cnt)) ]
then
    echo "All files copied successfully"
else
    echo "$cp_cnt files copied"
fi
IFS=$SAVEIFS
